apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-external
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.appExternal.type }}
  ports:
    - port: {{ .Values.service.appExternal.port }}
      targetPort: {{ .Values.service.appExternal.targetPort }}
      nodePort: {{ .Values.service.appExternal.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}