name: CI

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t honeycomb_web-app .

      - name: Run linting in container
        run: docker run --rm honeycomb_web-app npm run lint

      - name: Run tests in container
        # TEMPORARY WORKAROUND: https://github.com/marcstreeter/honeycomb-web/issues/23
        run: docker run --rm honeycomb_web-app npm run test || true

      - name: Build application in container
        run: docker run --rm honeycomb_web-app npm run build 